name: Get-IssueFormData
description: Get the data from a issue that was generated based on a issue form
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  IssueBody:
    description: The body of the issue
    required: false
    default: ${{ github.event.issue.body }}

outputs:
  data:
    description: The data from the issue body
    value: ${{ fromJson(steps.Get-IssueFormData.outputs.result).data }}

runs:
  using: composite
  steps:
    - name: Get-IssueFormData
      id: Get-IssueFormData
      uses: PSModule/GitHub-Script@v1
      env:
        GITHUB_ACTION_INPUT_IssueBody: ${{ inputs.IssueBody }}
      with:
        Script: . (Join-Path -Path '${{ github.action_path }}' -ChildPath 'scripts\main.ps1')
