name: Get-IssueFormData
description: Get the data from an issue that was generated based on an issue form
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  IssueBody:
    description: The body of the issue, if not provided it will use the body of the issue that triggered the workflow.
    required: false
    default: ${{ github.event.issue.body }}

outputs:
  data:
    description: The data from the issue body
    value: ${{ fromJson(steps.Get-IssueFormData.outputs.result).data }}

runs:
  using: composite
  steps:
    - name: Get-IssueFormData
      id: Get-IssueFormData
      uses: PSModule/GitHub-Script@0097f3bbe3f413f3b577b9bcc600727b0ca3201a # v1.7.10
      env:
        GITHUB_ACTION_INPUT_IssueBody: ${{ inputs.IssueBody }}
      with:
        Token: ''
        ShowOutput: true
        Script: |
          # Get-IssueFormData
          ${{ github.action_path }}/src/main.ps1
