name: Get-IssueFormData
description: Get the data from a issue that was generated based on a issue form
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  IssueBody:
    description: The body of the issue
    required: false
    default: ${{ github.event.issue.body }}

outputs:
  data:
    description: The data from the issue body
    value: ${{ steps.Get-IssueFormData.outputs.data }}

runs:
  using: composite
  steps:
    - name: Get-IssueFormData
      id: Get-IssueFormData
      shell: pwsh
      env:
        GITHUB_ACTION_INPUT_IssueBody: ${{ inputs.IssueBody }}
      run: |
        # Get-IssueFormData
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose
