name: Get-IssueFormData
description: Get the data from a issue that was generated based on a issue form
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  IssueBody:
    description: The body of the issue, if not provided it will use the body of the issue that triggered the workflow.
    required: false
    default: ${{ github.event.issue.body }}

outputs:
  data:
    description: The data from the issue body
    value: ${{ fromJson(steps.Get-IssueFormData.outputs.result).data }}

runs:
  using: composite
  steps:
    - name: Get-IssueFormData
      id: Get-IssueFormData
      uses: PSModule/GitHub-Script@v1
      env:
        GITHUB_ACTION_INPUT_IssueBody: ${{ inputs.IssueBody }}
      with:
        ShowOutput: true
        Script: |
          # Get-IssueFormData
          ${{ github.action_path }}\scripts\main.ps1
